server:
  port: 8081

spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://192.168.31.154:3306/vagetable?characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        validation-query: SELECT 1 FROM DUAL
logging:
  level:
    root: info

crypto:
  mode: aes
  aes:
    key: 123456
  rsa:
    public-key: 123456
    private-key: 123456