server:
  port: 8081
spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://192.168.31.154:3306/vagetable?characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        validation-query: SELECT 1 FROM DUAL
  data:
    redis:
      host: 192.168.31.154
      port: 6379
      database: 0
logging:
  level:
    root: info
security:
  auth:
    login-path: /swift/auth/login
    white-list: /swift/auth/**, /swagger-ui/**, /v3/api-docs/**
crypto:
  mode: aes
  aes:
    key: QWdUalAyUzlocktZRHVMampIYXFsY3E2TkxxOVV2U2h4c1NFdGEySVBjdz0=
  rsa:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApMF8Arlbxs04rO3nj0smc7AKbTSPEOapaPaI5R3gFIRXdOMtXU5U/8k95mC25duCssQeooDDdWu7KD8Ze+C2vSG03NpR6g6+ISSsDvN+BF+xEr1OwqgJXeeEk7ZaVuWS1c/bo/U1BDLOvYqXRRV6KbNyWmO5RkAMBoCgqrabtDm3AiRd9vImA0xotef2z4lNJtxULpj9jU9lV8QCijQV83V6fqNthtYQz8CDVNFQFVUunD8KXicj35AlAaqvJackd3d4pQZ/tF5VFHoPErPfQmgPjWT7pl49WC3feAbMqRx8uw2KZydRgPuyUS1lAglW/y67TLZ3F3ppQSvc+hyEHwIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkwXwCuVvGzTis7eePSyZzsAptNI8Q5qlo9ojlHeAUhFd04y1dTlT/yT3mYLbl24KyxB6igMN1a7soPxl74La9IbTc2lHqDr4hJKwO834EX7ESvU7CqAld54STtlpW5ZLVz9uj9TUEMs69ipdFFXops3JaY7lGQAwGgKCqtpu0ObcCJF328iYDTGi15/bPiU0m3FQumP2NT2VXxAKKNBXzdXp+o22G1hDPwINU0VAVVS6cPwpeJyPfkCUBqq8lpyR3d3ilBn+0XlUUeg8Ss99CaA+NZPumXj1YLd94BsypHHy7DYpnJ1GA+7JRLWUCCVb/LrtMtncXemlBK9z6HIQfAgMBAAECggEAGDz0ywvM8jLX3y0Cz4RtTEC+T/GXCJP+oVf/rMFX6XzMxv/y+RKgk57eEenxjmBcWoNaxGpwFvK57oJV8/ELwUhXrNQbj/UKSKL2Ax8UT31qdgjOsPl6o0t/qCGAKd+NWhJBzF2zJoJ5As6EUaAGwGLLdHvOUoTyn/RFbsf9oSZNv11RZGIsiUI5XFeTBrFTsHVEJmCN03EBynmcXkOWM3cofhUACII9X29PA2TIIbZTCT/gVXLN8ZNiZQCDdy2iRUsLy0xN5DuxmR2XiccktxV0nUVfvSLU0ujRFs02hoOu2Gq1eBkyCkluGWwy9RXa0jy5x+UVWNLTGe6kkVm6oQKBgQDkUZDspN8arsp+Iphp6ILa5yfq6j4NtKDhKZjeW/b+vH8XCKcUebknmYd3I2wWRFnzrzB88k1DuJXLr+NONoasijQIhImFqHf1eFALJd7RNrYkHq8tBFQWykGZEza4koKnZLCGzdZuETlz6BTXxfaQSkbpBLYjEILHP/xs9JIpPwKBgQC4uxa4vWU2ETEJPbjznH95EKtT3MVZ+XN/o/SOCHTdJPNjp1Ulx3/6raX9y+Sbm2oC5knXL+Sr+yHOSJS+vJ9cfMSY6ix3ZZ3PyJSTxf7La8S59dVB8pHU8NaYbDZ3ld8wyuy3RHBBe9qbsPNedLoOOMLOvySodvVnizjZqJMNIQKBgBFl7cc6oQ2leCS4eijH4QDRUIdkJiphM0k1JEL9ewraTkzxCdpTlDpiRqJbfqcLulcJaIZ86EpazH9i/c099nE7bs+fWeNnfQyliGPxFNOYebSy6eJiTA4Yh3skrazO7UnYMGN1V/u3MEuWyc/PdAR2xISJKV/uqCiKxa9/y4t9AoGAKBLl7fOgJid6lL+gBLD5ckDsecfVxBv6M0FVBw7Mk0C1z/N35DcwCyhqbvExSZRgXfqpIBZSrABRqBdUtT/j7kNevrFmLgyMPIwNtzTnfieFyLWMqr69Zg1M8EnhUvXfMg2DZophM8Nze/zZ/q6hwf4MPJ94i1crC2hHT+hi5iECgYEAsM3TuigC0aQa80EyQTGdgrf+dZN45HqJmR3myyLy0iQSlar6Uk52ptH7t4PZwZzVFMnV55NcPtwRhonbI2H6GQ2WPfK5Fu0Fo0nJdLu6P/e3CqAe+1e+h+SYaT8laOCVDbMm0LKVpRjz7QQziTLqqBKBoRqLS6h2Y6pLH5I+QJU=
