server:
  port: 8081

spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://192.168.31.154:3306/vagetable?characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        validation-query: SELECT 1 FROM DUAL
  data:
    redis:
      host: 192.168.31.154
      port: 6379
      database: 0
logging:
  level:
    root: info
security:
  auth:
    login-path: /swift/auth/login
    white-list: /swift/auth/**, /swagger-ui/**, /v3/api-docs/**
crypto:
  mode: aes
  aes:
    key: 123456
  rsa:
    public-key: 123456
    private-key: 123456